### PR TITLE
adds resources to OPM gas giants

### PR DESCRIPTION
**Pull request by gabevenberg**
just a quick thing i wrote for my install, may be nice to have.

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
Can you place this in the ResourceDefs folder?

**Comment by gabevenberg** [comment]
done!

**Comment by ChrisAdderley** [comment]
Ah sorry I forgot to mention. dev has diverged from master, so you'll need to rebase off dev.

**Comment by gabevenberg** [comment]
now to learn how to use GIT CLI...

**Comment by ChrisAdderley** [comment]
it's a good skill to have haha!

**Comment by gabevenberg** [comment]
Not my first time with CLI to be fair, but git...
https://xkcd.com/1597/

**Comment by gabevenberg** [comment]
redoing my fork, closing this one. (learning git, want to learn how to do this purely local)

**Pull request closed without merging**
