### PR TITLE
Rename ModulePulseEngine to ModuleFFTPulseEngine

### PR DESCRIPTION
**Pull request by Calvin-13**
Allows for compatibility with Stockish Project Orion

### CODE REVIEW

**Comment by Calvin-13** [comment]
Weird, changing a comment seems to break the PKMC "build and deploy" scripts. Not familiar with Python, so I don't see why this would happen.

**Comment by ChrisAdderley** [comment]
It's because you are targeting master rather than dev.

I'm closing this because I've already done this actually... But thanks.

**Comment by Calvin-13** [comment]
Apologies, I couldn't have known.

**Comment by ChrisAdderley** [comment]
Yeah no need to apologize!

**Pull request closed without merging**
